# -*- coding: utf-8 -*-
"""clustering.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_rW5WBI7Fd91S7KMvAumFd3AVnUkIW0I
"""

from sklearn.cluster import KMeans
from sklearn.cluster import AgglomerativeClustering

def k_means():
   k = 3

# Apply K-Means
   kmeans = KMeans(n_clusters=k, random_state=1234, n_init=200)
   labels_kmeans = kmeans.fit_predict(X_tfidf)

def hierarchical():
   hierarchical = AgglomerativeClustering(n_clusters=k, linkage='ward')
   labels_hierarchical = hierarchical.fit_predict(X_tfidf.toarray())

